<a href="https://colab.research.google.com/github/israrahmadzak/diabetes-xai-mphil/blob/main/MPhil_Diabetes_NHANES_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

BASE_PATH = "/content/drive/MyDrive/MPhil_Diabetes_Thesis"

folders = [
    "01_Data/NHANES",
    "01_Data/Pakistan",
    "03_Results",
    "04_Figures",
    "05_Models"
]

for f in folders:
    os.makedirs(os.path.join(BASE_PATH, f), exist_ok=True)

print("Project structure ready!")

Project structure ready!

In [5]:
path = "/content/drive/MyDrive/MPhil_Diabetes_Thesis/01_Data/NHANES"
import os
os.listdir(path)

['ACQ_J.xpt',
 'TRIGLY_J.xpt',
 'TCHOL_J.xpt',
 'HDL_J.xpt',
 'GHB_J.xpt',
 'GLU_J.xpt',
 'BMX_J.xpt',
 'PAQ_J.xpt',
 'BPX_J.xpt',
 'DEMO_J.xpt',
 'SMQ_J.xpt',
 'DIQ_J.xpt']

In [6]:
import os
import pandas as pd

base_path = "/content/drive/MyDrive/MPhil_Diabetes_Thesis/01_Data/NHANES"

files = os.listdir(base_path)
files

['ACQ_J.xpt',
 'TRIGLY_J.xpt',
 'TCHOL_J.xpt',
 'HDL_J.xpt',
 'GHB_J.xpt',
 'GLU_J.xpt',
 'BMX_J.xpt',
 'PAQ_J.xpt',
 'BPX_J.xpt',
 'DEMO_J.xpt',
 'SMQ_J.xpt',
 'DIQ_J.xpt']

In [7]:
demo = pd.read_sas(base_path + "/DEMO_J.xpt")
bmx  = pd.read_sas(base_path + "/BMX_J.xpt")
bpx  = pd.read_sas(base_path + "/BPX_J.xpt")
glu  = pd.read_sas(base_path + "/GLU_J.xpt")
ghb  = pd.read_sas(base_path + "/GHB_J.xpt")
tchol = pd.read_sas(base_path + "/TCHOL_J.xpt")
hdl  = pd.read_sas(base_path + "/HDL_J.xpt")
trig = pd.read_sas(base_path + "/TRIGLY_J.xpt")
paq  = pd.read_sas(base_path + "/PAQ_J.xpt")
smq  = pd.read_sas(base_path + "/SMQ_J.xpt")
diq  = pd.read_sas(base_path + "/DIQ_J.xpt")

print("Loaded all datasets")

Loaded all datasets

In [8]:
df = demo.merge(bmx, on="SEQN", how="left")
df = df.merge(bpx, on="SEQN", how="left")
df = df.merge(glu, on="SEQN", how="left")
df = df.merge(ghb, on="SEQN", how="left")
df = df.merge(tchol, on="SEQN", how="left")
df = df.merge(hdl, on="SEQN", how="left")
df = df.merge(trig, on="SEQN", how="left")
df = df.merge(paq, on="SEQN", how="left")
df = df.merge(smq, on="SEQN", how="left")
df = df.merge(diq, on="SEQN", how="left")

print(df.shape)

(9254, 208)

In [9]:
df["target"] = df["DIQ010"].apply(lambda x: 1 if x == 1 else 0)

df["target"].value_counts()

target
0    8361
1     893
Name: count, dtype: int64

In [10]:
import numpy as np

df = df.replace("?", np.nan)

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

In [11]:
df.to_csv(base_path + "/final_nhanes.csv", index=False)

print("✅ Final NHANES dataset saved")

✅ Final NHANES dataset saved

In [12]:
print("Total samples (rows):", df.shape[0])
print("Total features (columns):", df.shape[1])

Total samples (rows): 9254
Total features (columns): 209

In [13]:
print(df.columns.tolist())

['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC', 'DMDBORN4', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA', 'DMDHHSIZ', 'DMDFMSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRGND', 'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA', 'INDHHIN2', 'INDFMIN2', 'INDFMPIR', 'BMDSTATS', 'BMXWT', 'BMIWT', 'BMXRECUM', 'BMIRECUM', 'BMXHEAD', 'BMIHEAD', 'BMXHT', 'BMIHT', 'BMXBMI', 'BMXLEG', 'BMILEG', 'BMXARML', 'BMIARML', 'BMXARMC', 'BMIARMC', 'BMXWAIST', 'BMIWAIST', 'BMXHIP', 'BMIHIP', 'PEASCCT1', 'BPXCHR', 'BPAARM', 'BPACSZ', 'BPXPLS', 'BPXPULS', 'BPXPTY', 'BPXML1', 'BPXSY1', 'BPXDI1', 'BPAEN1', 'BPXSY2', 'BPXDI2', 'BPAEN2', 'BPXSY3', 'BPXDI3', 'BPAEN3', 'BPXSY4', 'BPXDI4', 'BPAEN4', 'WTSAF2YR_x', 'LBXGLU', 'LBDGLUSI', 'LBXGH', 'LBXTC', 'LBDTCSI', 'LBDHDD', 'LBDHDDSI', 'WTSAF2YR_y', 'LBXTR', 'LBDTRSI', 'LBDLDL', 'LBDLDLSI', 'LBDLDLM', 'LBDLDMSI', 'LBDLDLN', 'LBDLDNSI', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMQ890', 'SMQ895', 'SMQ900', 'SMQ905', 'SMQ910', 'SMQ915', 'SMAQUEX2', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'target']

In [14]:
print("Numerical features:", len(df.select_dtypes(include=['int64', 'float64']).columns))
print("Categorical features:", len(df.select_dtypes(include=['object']).columns))

Numerical features: 207
Categorical features: 2

In [15]:
df["target"].value_counts()

target
0    8361
1     893
Name: count, dtype: int64

In [16]:
ratio = df["target"].value_counts(normalize=True)
print(ratio)

target
0    0.903501
1    0.096499
Name: proportion, dtype: float64

In [18]:
from xgboost import XGBClassifier

In [19]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight = 8361/893   # IMPORTANT
)

In [20]:
X = df.drop(columns=["target"])
y = df["target"]

print(X.shape, y.shape)

(9254, 208) (9254,)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [24]:
X = df.drop(columns=["target"])

print(X.dtypes)

SEQN        float64
SDDSRVYR    float64
RIDSTATR    float64
RIAGENDR    float64
RIDAGEYR    float64
             ...
DID341      float64
DID350      float64
DIQ350U     float64
DIQ360      float64
DIQ080      float64
Length: 208, dtype: object

In [25]:
import numpy as np

# convert empty bytes / strings to NaN
X = X.replace(b'', np.nan)
X = X.replace('', np.nan)

In [26]:
for col in X.columns:
    if X[col].dtype == "object":
        X[col] = X[col].fillna(X[col].mode()[0])
    else:
        X[col] = X[col].fillna(X[col].median())

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [29]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

ValueError: could not convert string to float: b'* NO MATCH *'

In [30]:
import numpy as np
import pandas as pd

X = df.drop(columns=["target"])

In [31]:
for col in X.columns:
    X[col] = X[col].astype(str)

In [32]:
X = X.replace(["* NO MATCH *", "* NAN *", "nan", "None", "b''"], np.nan)

/tmp/ipykernel_1842/3801717235.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.replace(["* NO MATCH *", "* NAN *", "nan", "None", "b''"], np.nan)

In [33]:
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors='ignore')

/tmp/ipykernel_1842/1955135617.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  X[col] = pd.to_numeric(X[col], errors='ignore')

In [34]:
for col in X.columns:
    if X[col].dtype == "object":
        X[col] = X[col].fillna(X[col].mode()[0])
    else:
        X[col] = X[col].fillna(X[col].median())

In [35]:
X = pd.get_dummies(X, drop_first=True)

In [36]:
lr.fit(X_train, y_train)

ValueError: could not convert string to float: b'* NO MATCH *'

In [37]:
import numpy as np
import pandas as pd

X = df.drop(columns=["target"]).copy()
y = df["target"].copy()

In [38]:
# Replace NHANES garbage values
X = X.replace(["* NO MATCH *", "* NAN *", "b'* NO MATCH *'", "", "nan"], np.nan)

# Convert all to numeric where possible
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors='coerce')

In [39]:
for col in X.columns:
    X[col] = X[col].fillna(X[col].median())

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [41]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [42]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [43]:
X = df.drop(columns=["target"])
y = df["target"]

In [44]:
X = pd.get_dummies(X, drop_first=True)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [46]:
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),  # FIXES NaN
    ("scaler", StandardScaler()),                   # normalization
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

In [47]:
pipeline.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['BMIHEAD']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [48]:
y_pred = pipeline.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['BMIHEAD']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

In [49]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       0.99      1.00      0.99       179

    accuracy                           1.00      1851
   macro avg       0.99      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

In [50]:
df.columns[df.columns.str.contains("DIQ")]

Index(['DIQ010', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C',
       'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I',
       'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O',
       'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U',
       'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DIQ060U',
       'DIQ070', 'DIQ230', 'DIQ240', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291',
       'DIQ300S', 'DIQ300D', 'DIQ350U', 'DIQ360', 'DIQ080'],
      dtype='object')

In [51]:
X = df.drop(columns=["target"])

# REMOVE leakage columns
leak_cols = [col for col in X.columns if "DIQ" in col]
X = X.drop(columns=leak_cols, errors="ignore")

In [52]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [53]:
pipeline.fit(X_train, y_train)

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: b''

In [54]:
import numpy as np
import pandas as pd

X = df.drop(columns=["target"]).copy()

# Convert EVERYTHING to string first (safe cleanup)
X = X.astype(str)

# Replace all NHANES garbage values
X = X.replace([
    "b''",
    "b'* NO MATCH *'",
    "* NO MATCH *",
    "nan",
    "NaN",
    "",
    "None"
], np.nan)

/tmp/ipykernel_1842/2304058723.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.replace([

In [55]:
X = X.apply(pd.to_numeric, errors='coerce')

In [56]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")
X_clean = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['BMIHEAD' 'SMD100BR']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

ValueError: Shape of passed values is (9254, 206), indices imply (9254, 208)

In [57]:
X = X.dropna(axis=1, how='all')

In [58]:
X = X.loc[:, X.nunique() > 1]

In [59]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_clean = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index=X.index
)

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [62]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

In [63]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [64]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight = (len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [65]:
from sklearn.metrics import classification_report, roc_auc_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))

In [66]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.91      0.96      0.93      1672
           1       0.16      0.06      0.09       179

    accuracy                           0.88      1851
   macro avg       0.53      0.51      0.51      1851
weighted avg       0.83      0.88      0.85      1851

ROC-AUC: 0.6419168159097591

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      1.00      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      1.00      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0

In [67]:
[col for col in X_clean.columns if "DIQ" in col]

['DIQ010',
 'DIQ160',
 'DIQ170',
 'DIQ172',
 'DIQ175A',
 'DIQ180',
 'DIQ050',
 'DIQ060U',
 'DIQ070',
 'DIQ230',
 'DIQ240',
 'DIQ260U',
 'DIQ275',
 'DIQ280',
 'DIQ291',
 'DIQ300S',
 'DIQ300D',
 'DIQ350U',
 'DIQ360',
 'DIQ080']

In [68]:
X_clean = X_clean.drop(columns=[
    col for col in X_clean.columns if "DIQ" in col
], errors="ignore")

In [69]:
leak_cols = ["GLU", "GHB", "HbA1c", "DIQ010"]
X_clean = X_clean.drop(columns=leak_cols, errors="ignore")

In [71]:
lr_prob  = lr.predict_proba(X_test)[:,1]
rf_prob  = rf.predict_proba(X_test)[:,1]
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/MPhil_Diabetes_Thesis/01_Data/NHANES/final_nhanes.csv"
)

print(df.shape)

(9254, 209)

In [4]:
# Check current feature count
print(X_clean.shape)

# Split again
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

NameError: name 'X_clean' is not defined

In [5]:
import os

os.listdir('/content')

['.config', 'drive', 'sample_data']

In [6]:
import os

files = os.listdir('/content')
for f in files:
    print(f)

.config
drive
sample_data

In [7]:
import os

os.listdir('/content/drive/MyDrive')

['How to get started with Drive.pdf',
 'Study-Plan sample.docx',
 'sample study plan.docx',
 'sample study plan.gdoc',
 'CSC simple tips.gdoc',
 '7th SEMESTER.rar',
 'Pictures of KPITB ',
 '硕士预录函_656.pdf',
 'LIST OF TRAVEL AGENCIES IN KPK UPTO 23.01.2020.pdf',
 'Israr Ahmad academics documents',
 'final year thesis',
 'Salary slip ( 00934572 March , 2021 ).PDF',
 'TrustWalletBackup',
 'DOC-20241008-WA0021..pdf',
 'Contact Information.gform',
 'Apply for Scholarship Test – Samarbagh Model College  .gform',
 'Untitled form (File responses)',
 'Untitled form.gform',
 'israr-Resume.pdf',
 'xgb_model.pkl',
 'diabetes_app',
 'NHANES_Project',
 'Colab Notebooks',
 'MPhil_Diabetes',
 'diabetes-xai-mphil',
 'DIABETES_PAKISTAN_PROJECT',
 'MPhil_Diabetes_Thesis']

In [8]:
import os

os.listdir('/content/drive/MyDrive/MPhil_Diabetes_Thesis')

['01_Data', '03_Results', '04_Figures', '05_Models']

In [9]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive/MPhil_Diabetes_Thesis'):
    for file in files:
        if file.endswith('.csv'):
            print(os.path.join(root, file))

/content/drive/MyDrive/MPhil_Diabetes_Thesis/01_Data/NHANES/final_nhanes.csv

In [10]:
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.pkl'):
            print(os.path.join(root, file))

/content/drive/MyDrive/xgb_model.pkl
/content/drive/MyDrive/diabetes_app/diabetes_xgb_model.pkl
/content/drive/MyDrive/NHANES_Project/models/model2_early.pkl
/content/drive/MyDrive/MPhil_Diabetes/models/xgb_model.pkl
/content/drive/MyDrive/MPhil_Diabetes/models/xgboost.pkl
/content/drive/MyDrive/diabetes-xai-mphil/models/all_models.pkl

In [11]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/MPhil_Diabetes_Thesis/01_Data/NHANES/final_nhanes.csv"
)

print(df.shape)
df.head()

(9254, 209)

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DID310S,DID310D,DID320,DID330,DID341,DID350,DIQ350U,DIQ360,DIQ080,target
0,93703.0,10.0,2.0,2.0,2.0,10.0,5.0,6.0,2.0,27.0,...,6666.0,6666.0,9999.0,9999.0,2.0,1.0,1.0,2.0,2.0,0
1,93704.0,10.0,2.0,1.0,2.0,10.0,3.0,3.0,1.0,33.0,...,6666.0,6666.0,9999.0,9999.0,2.0,1.0,1.0,2.0,2.0,0
2,93705.0,10.0,2.0,2.0,66.0,10.0,4.0,4.0,2.0,106.0,...,6666.0,6666.0,9999.0,9999.0,2.0,1.0,1.0,2.0,2.0,0
3,93706.0,10.0,2.0,1.0,18.0,10.0,5.0,6.0,2.0,222.0,...,6666.0,6666.0,9999.0,9999.0,2.0,1.0,1.0,2.0,2.0,0
4,93707.0,10.0,2.0,1.0,13.0,10.0,5.0,7.0,2.0,158.0,...,6666.0,6666.0,9999.0,9999.0,2.0,1.0,1.0,2.0,2.0,0

In [12]:
print(df.columns.tolist())

['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC', 'DMDBORN4', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA', 'DMDHHSIZ', 'DMDFMSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRGND', 'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA', 'INDHHIN2', 'INDFMIN2', 'INDFMPIR', 'BMDSTATS', 'BMXWT', 'BMIWT', 'BMXRECUM', 'BMIRECUM', 'BMXHEAD', 'BMIHEAD', 'BMXHT', 'BMIHT', 'BMXBMI', 'BMXLEG', 'BMILEG', 'BMXARML', 'BMIARML', 'BMXARMC', 'BMIARMC', 'BMXWAIST', 'BMIWAIST', 'BMXHIP', 'BMIHIP', 'PEASCCT1', 'BPXCHR', 'BPAARM', 'BPACSZ', 'BPXPLS', 'BPXPULS', 'BPXPTY', 'BPXML1', 'BPXSY1', 'BPXDI1', 'BPAEN1', 'BPXSY2', 'BPXDI2', 'BPAEN2', 'BPXSY3', 'BPXDI3', 'BPAEN3', 'BPXSY4', 'BPXDI4', 'BPAEN4', 'WTSAF2YR_x', 'LBXGLU', 'LBDGLUSI', 'LBXGH', 'LBXTC', 'LBDTCSI', 'LBDHDD', 'LBDHDDSI', 'WTSAF2YR_y', 'LBXTR', 'LBDTRSI', 'LBDLDL', 'LBDLDLSI', 'LBDLDLM', 'LBDLDMSI', 'LBDLDLN', 'LBDLDNSI', 'PAQ605', 'PAQ610', 'PAD615', 'PAQ620', 'PAQ625', 'PAD630', 'PAQ635', 'PAQ640', 'PAD645', 'PAQ650', 'PAQ655', 'PAD660', 'PAQ665', 'PAQ670', 'PAD675', 'PAD680', 'SMQ020', 'SMD030', 'SMQ040', 'SMQ050Q', 'SMQ050U', 'SMD057', 'SMQ078', 'SMD641', 'SMD650', 'SMD093', 'SMDUPCA', 'SMD100BR', 'SMD100FL', 'SMD100MN', 'SMD100LN', 'SMD100TR', 'SMD100NI', 'SMD100CO', 'SMQ621', 'SMD630', 'SMQ661', 'SMQ665A', 'SMQ665B', 'SMQ665C', 'SMQ665D', 'SMQ670', 'SMQ848', 'SMQ852Q', 'SMQ852U', 'SMQ890', 'SMQ895', 'SMQ900', 'SMQ905', 'SMQ910', 'SMQ915', 'SMAQUEX2', 'DIQ010', 'DID040', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ050', 'DID060', 'DIQ060U', 'DIQ070', 'DIQ230', 'DIQ240', 'DID250', 'DID260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ291', 'DIQ300S', 'DIQ300D', 'DID310S', 'DID310D', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ350U', 'DIQ360', 'DIQ080', 'target']

In [13]:
print(df["target"].value_counts())

target
0    8361
1     893
Name: count, dtype: int64

In [14]:
for col in df.columns:
    if "DIQ" in col.upper() or "GLU" in col.upper() or "GHB" in col.upper():
        print(col)

LBXGLU
LBDGLUSI
DIQ010
DIQ160
DIQ170
DIQ172
DIQ175A
DIQ175B
DIQ175C
DIQ175D
DIQ175E
DIQ175F
DIQ175G
DIQ175H
DIQ175I
DIQ175J
DIQ175K
DIQ175L
DIQ175M
DIQ175N
DIQ175O
DIQ175P
DIQ175Q
DIQ175R
DIQ175S
DIQ175T
DIQ175U
DIQ175V
DIQ175W
DIQ175X
DIQ180
DIQ050
DIQ060U
DIQ070
DIQ230
DIQ240
DIQ260U
DIQ275
DIQ280
DIQ291
DIQ300S
DIQ300D
DIQ350U
DIQ360
DIQ080

In [15]:
leak_cols = [
    col for col in df.columns
    if col.startswith("DIQ") or "GLU" in col or "GHB" in col
]

df_clean = df.drop(columns=leak_cols, errors="ignore")

print(df_clean.shape)

(9254, 164)

In [16]:
X = df_clean.drop(columns=["target"])
y = df_clean["target"]

In [17]:
X = X.apply(pd.to_numeric, errors='coerce')

In [18]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns
)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['BMIHEAD' 'SMDUPCA' 'SMD100BR']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

ValueError: Shape of passed values is (9254, 160), indices imply (9254, 163)

In [19]:
# Drop columns with ALL missing values first
X = X.dropna(axis=1, how='all')

In [20]:
# Remove columns with only 1 unique value
X = X.loc[:, X.nunique() > 1]

In [21]:
from sklearn.impute import SimpleImputer
import pandas as pd

imputer = SimpleImputer(strategy="median")

X_clean_array = imputer.fit_transform(X)

X_clean = pd.DataFrame(
    X_clean_array,
    columns=X.columns,   # NOW MATCHES
    index=X.index
)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [24]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [25]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight = (len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [26]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [27]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

NameError: name 'lr_pred' is not defined

In [28]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [29]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [30]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight=(len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [31]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [32]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.98      0.89      0.94      1672
           1       0.46      0.84      0.60       179

    accuracy                           0.89      1851
   macro avg       0.72      0.87      0.77      1851
weighted avg       0.93      0.89      0.90      1851

ROC-AUC: 0.9308525567346502
PR-AUC: 0.8323468015396884

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      1.00      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0
PR-AUC: 1.0

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      1.00      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0
PR-AUC: 1.0

In [33]:
import pandas as pd

importance = pd.DataFrame({
    "feature": X_clean.columns,
    "importance": xgb.feature_importances_
}).sort_values(by="importance", ascending=False)

importance.head(20)

      feature  importance
79      LBXGH    0.453530
149    DID341    0.165592
141    DID040    0.097803
144    DID260    0.049170
146   DID310D    0.036323
143    DID250    0.034741
145   DID310S    0.032294
148    DID330    0.028792
3    RIDAGEYR    0.020579
142    DID060    0.014545
150    DID350    0.011082
108    PAD680    0.006736
87     LBDLDL    0.006478
36   DMDHRMAZ    0.006168
107    PAD675    0.006140
16   DMDMARTL    0.003709
69     BPXSY2    0.003051
82     LBDHDD    0.003025
104    PAD660    0.002595
65     BPXML1    0.001815

In [34]:
X_clean = X_clean.drop(columns=["LBXGH"], errors="ignore")

In [35]:
X_clean = X_clean.drop(columns=["LBXGH"], errors="ignore")

In [36]:
X_clean.shape

(9254, 150)

In [37]:
X_clean.columns

Index(['SEQN', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1',
       'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ',
       ...
       'DID040', 'DID060', 'DID250', 'DID260', 'DID310S', 'DID310D', 'DID320',
       'DID330', 'DID341', 'DID350'],
      dtype='object', length=150)

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [40]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [41]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [42]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight=(len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [43]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [44]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.98      0.89      0.93      1672
           1       0.45      0.85      0.59       179

    accuracy                           0.88      1851
   macro avg       0.71      0.87      0.76      1851
weighted avg       0.93      0.88      0.90      1851

ROC-AUC: 0.9311666354815429
PR-AUC: 0.829835036612376

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0
PR-AUC: 1.0000000000000004

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 0.9999966587367352
PR-AUC: 0.999968963376785

In [45]:
X_clean = X_clean.drop(
    columns=[col for col in X_clean.columns if col.startswith("DID")],
    errors="ignore"
)

In [46]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [47]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [48]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight=(len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [49]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [50]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.98      0.89      0.93      1672
           1       0.45      0.85      0.59       179

    accuracy                           0.88      1851
   macro avg       0.71      0.87      0.76      1851
weighted avg       0.93      0.88      0.90      1851

ROC-AUC: 0.9311666354815429
PR-AUC: 0.829835036612376

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0
PR-AUC: 1.0000000000000004

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 0.9999966587367352
PR-AUC: 0.999968963376785

In [51]:
safe_features = [
    "RIDAGEYR",   # Age
    "RIAGENDR",   # Gender
    "BMXBMI",     # BMI
    "BPXSY1", "BPXDI1",  # Blood pressure
    "BMXWAIST",   # Waist
]

In [52]:
X_safe = df[safe_features]
y = df["target"]

In [53]:
from sklearn.impute import SimpleImputer
import pandas as pd

imputer = SimpleImputer(strategy="median")

X_safe = pd.DataFrame(
    imputer.fit_transform(X_safe),
    columns=safe_features
)

In [54]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [55]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:,1]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [56]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [57]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight=(len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:,1]

In [58]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [59]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.98      0.89      0.93      1672
           1       0.45      0.85      0.59       179

    accuracy                           0.88      1851
   macro avg       0.71      0.87      0.76      1851
weighted avg       0.93      0.88      0.90      1851

ROC-AUC: 0.9311666354815429
PR-AUC: 0.829835036612376

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 1.0
PR-AUC: 1.0000000000000004

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1672
           1       1.00      0.99      1.00       179

    accuracy                           1.00      1851
   macro avg       1.00      1.00      1.00      1851
weighted avg       1.00      1.00      1.00      1851

ROC-AUC: 0.9999966587367352
PR-AUC: 0.999968963376785

In [60]:
safe_features = [
    # Demographics
    "RIDAGEYR",   # Age
    "RIAGENDR",   # Gender

    # Body measurements
    "BMXBMI",     # BMI
    "BMXWAIST",   # Waist circumference

    # Blood pressure
    "BPXSY1",
    "BPXDI1",

    # Lifestyle (if available in your dataset)
    "PAQ650",     # Physical activity
    "SMQ020",     # Smoking status

    # Socioeconomic
    "INDFMPIR"    # Income-to-poverty ratio
]

In [61]:
missing = [col for col in safe_features if col not in df.columns]
print("Missing columns:", missing)

Missing columns: []

In [62]:
X = df[[col for col in safe_features if col in df.columns]]
y = df["target"]

In [63]:
from sklearn.impute import SimpleImputer
import pandas as pd

imputer = SimpleImputer(strategy="median")

X_clean = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns
)

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [67]:
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
lr_prob = lr.predict_proba(X_test)[:, 1]

In [68]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:, 1]

In [69]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    scale_pos_weight=(len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_prob = xgb.predict_proba(X_test)[:, 1]

In [70]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

def evaluate(name, y_test, pred, prob):
    print("\n====================", name, "====================")
    print(classification_report(y_test, pred))
    print("ROC-AUC:", roc_auc_score(y_test, prob))
    print("PR-AUC:", average_precision_score(y_test, prob))

In [71]:
evaluate("Logistic Regression", y_test, lr_pred, lr_prob)
evaluate("Random Forest", y_test, rf_pred, rf_prob)
evaluate("XGBoost", y_test, xgb_pred, xgb_prob)

==================== Logistic Regression ====================
              precision    recall  f1-score   support

           0       0.98      0.72      0.83      1672
           1       0.25      0.87      0.39       179

    accuracy                           0.73      1851
   macro avg       0.61      0.79      0.61      1851
weighted avg       0.91      0.73      0.79      1851

ROC-AUC: 0.8598523829889604
PR-AUC: 0.36084578805034256

==================== Random Forest ====================
              precision    recall  f1-score   support

           0       0.98      0.77      0.86      1672
           1       0.28      0.84      0.43       179

    accuracy                           0.78      1851
   macro avg       0.63      0.81      0.64      1851
weighted avg       0.91      0.78      0.82      1851

ROC-AUC: 0.8595349629788029
PR-AUC: 0.33810444708296505

==================== XGBoost ====================
              precision    recall  f1-score   support

           0       0.98      0.75      0.85      1672
           1       0.27      0.86      0.41       179

    accuracy                           0.76      1851
   macro avg       0.63      0.81      0.63      1851
weighted avg       0.91      0.76      0.81      1851

ROC-AUC: 0.8625103579161209
PR-AUC: 0.339775770303593